apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: apps

commonLabels:
  environment: dev

replicas:
  - name: inventory
    count: 1

images:
  - name: 905418008419.dkr.ecr.us-east-1.amazonaws.com/spikeadmin
    newTag: 0.4.9
