apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigateway
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:905418008419:certificate/6b67c1ab-77c8-423f-a5e3-aa088621ed8e'
    alb.ingress.kubernetes.io/subnets: 'subnet-08968acd8ab666264,subnet-0a6e13fd2faeb8d2f'
spec:
  ingressClassName: alb
  tls:
    - hosts:
      - auth.saamsksa.com
      secretName: auth-api-tls-secret
  rules:
    - http:
        paths:             
        - path: /
          pathType: Prefix
          backend:
            service:
              name: auth-api-service
              port:
                number: 8071
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: authapi
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/subnets: 'subnet-08968acd8ab666264,subnet-0a6e13fd2faeb8d2f'
# spec:
#   ingressClassName: alb
#   rules:
#     - http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#               service:
#                 name: auth-api-service
#                 port:
#                   number: 8071
