apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: apps

commonLabels:
  environment: dev

images:
  - name: 905418008419.dkr.ecr.us-east-1.amazonaws.com/ordering-api
    newTag: 0.0.2
  - name: 905418008419.dkr.ecr.us-east-1.amazonaws.com/auth-api
    newTag: a0.4.1
